// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF-vu4DI0YPBfrVjMCLk_cafa-sk00H_I',
    appId: '1:863487650002:web:3c5eb57ffb93a8eb19e50b',
    messagingSenderId: '863487650002',
    projectId: 'flutter-prep-c32ba',
    authDomain: 'flutter-prep-c32ba.firebaseapp.com',
    databaseURL: 'https://flutter-prep-c32ba-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-c32ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwzf8m4KKaqhxlmTwLZQNocOG8Yk10cmA',
    appId: '1:863487650002:android:38728ff0b06225e319e50b',
    messagingSenderId: '863487650002',
    projectId: 'flutter-prep-c32ba',
    databaseURL: 'https://flutter-prep-c32ba-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-c32ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqpj0QnKCC0DCQKRyujnYtIoMZtVZ8S5U',
    appId: '1:863487650002:ios:577686f04376ff6119e50b',
    messagingSenderId: '863487650002',
    projectId: 'flutter-prep-c32ba',
    databaseURL: 'https://flutter-prep-c32ba-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-c32ba.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );
}
